url: "https://podcast.steakscience.com"

podcast:
  title: Nerding Out
  description: A podcast about things.
  url: /podcast.xml # podcast xml url
  author: Nirawit Jittipairoj
  email: podcast@steakscience.com
  logo: /assets/cover.jpg # logo in 1400 – 3000 pixel
  language: "en-us" # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: "Society &amp; Culture" # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: [subcategory]
  type: episodic # episodic | serial
  explicit: true # true | false
  complete: 'no' # 'yes' | 'no'
  block: 'no' # 'yes' | 'no'